apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudnorth

resources:
  - ../../base

commonLabels:
  environment: staging

patchesStrategicMerge:
  - frontend-deployment.yaml
  - backend-deployment.yaml

configMapGenerator:
  - name: cloudnorth-config
    behavior: merge
    literals:
      - environment=staging
      - log.level=info
